export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const REGISTER_USER = 'REGISTER_USER';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';

export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SUBSCRIBE_FEED = 'SUBSCRIBE_FEED';
export const SET_FEEDS = 'SET_FEEDS';
export const SET_CURRENT_FEED = 'SET_CURRENT_FEED';
export const SET_ARTICLES = 'SET_ARTICLES';
